### ISSUE TITLE
Meta TODO

### ISSUE THREAD

**Issue by raymak** [raymak/vpn-recommendation-shield-study#1]
## Code
- [x] investigate how to detect captive portal
- [x] design code architecture, including how the privileged and webextension code connect
- [x] implement triggers
- [x] implement pop-up panel
- [x] implement instrumentation

## Instrumentation
- [x] design event data pings
- [x] design summary data pings

## QA
- [x] design necessary QA tools
- [x] write QA scenarios

## Data Analysis 
- [ ] design analysis plan

## Approvals and Shipping
[How to ship a native study](https://docs.google.com/document/d/1hOMjZ7l1K0HL8DUp7HCr8BeRO7NGw0SwYjK2nfwtRJQ/edit?usp=sharing)

### Resources:
[Product Hypothesis Document](https://docs.google.com/document/d/14Rq1sfKYg8U2_-UKd3KR6qLBuBzsoEt6oSze4G5o4Ns/edit)
